final Map<String, String> trTR = {
  'settings_title': 'Ayarlar',
  'watermark': 'Filigran',
  'general': 'Genel',
  'more_apps': 'Diğer Uygulamalar',
  'rate_app': 'Uygulamayı Puanla',
  'share_app': 'Uygulamayı Paylaş',
  'privacy_policy': 'Gizlilik Politikası',
  'terms_conditions': 'Şartlar ve Koşullar',
  'access_title': 'Bazı erişimlere ihtiyacımız var!',
  'access_description':
  'Fotoğraf çekmek veya video kaydetmek için cihaz kamerası, fotoğraf galerisi ve konum erişimini onaylamanız gerekir.',
  'camera_access': 'Kamera Erişimi',
  'camera_desc': 'Fotoğraf çekmek ve fotoğraf üzerine damga eklemek için kamera erişimi gereklidir.',
  'location_access': 'Konum Erişimi',
  'location_desc': 'Mevcut konumunuzu göstermek için konum erişimi gereklidir.',
  'gallery_access': 'Fotoğraf ve Galeri Erişimi',
  'gallery_desc': 'Albümünüze göz atabilmek için fotoğraf galerisine erişim gereklidir.',
  'location_city': 'İstanbul, Türkiye',
  'saved_title': 'Kaydedildi',
  'banner_text': '📢 Bu bir reklam alanıdır',
};
